### ISSUE TITLE
[REQUEST] Darkplaces and Quakespasm support

### ISSUE THREAD

**Issue by IDDQD1337** [Immorpher/Bandither#1]
I hope to support other Quake source ports like Darkplaces and Quakespasm?

Perhaps it will be more difficult to adapt from, but it would be cool to know how it works on these source ports.

**Comment by Immorpher** [comment]
I'll have to check Darkplaces, however Quakespasm does not have direct shader support as far as I know. But you can use ReShade to give it shader support! I have tested ReShade with Quakespasm Spiked and it does work with Bandither. Just make sure to download the ReShade version and check the instructions. I suspect it should be fine with other versions of Quakespasm too.

**Comment by Immorpher** [comment]
It seems like there is some shader support in Darkplaces! I can look into implementing it :) https://quakeone.com/forum/quake-mod-releases/finished-works/12797-hgsz-s-retro-quake-glsl-retro-shaders-for-darkplaces

**Comment by IDDQD1337** [comment]
I think this is a good sign, it's a pity that Quakespasm can't be done with Zandronum
